---
# tasks file for installing python3
- name: install epel release
  package:
    name: epel-release
    state: present
- name: install {{item}}
  package:
    name: '{{  item  }}'
    state: present
  with_items:
    - 'python36'
    - 'python36-setuptools'
- name: install PIP
  shell: easy_install-3.6 pip
